### ISSUE TITLE
Financial Endpoints

### ISSUE THREAD

**Issue by bernas670** [bernas670/sinf#40]
Implement and document both endpoints needed for the financial overview.

**TODO**:
 - [ ] Implement `/balance_sheet`
 - [ ] Document `/balance_sheet`
 - [ ] Implement `/results_demonstration`
 - [ ] Document `/results_demonstration`
